// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiVjiYk4P_iupB825akQCiG3M2Wn5RSeU',
    appId: '1:211588944864:web:0dba6bc4d4e132fd119185',
    messagingSenderId: '211588944864',
    projectId: 'court-diary-ceadc',
    authDomain: 'court-diary-ceadc.firebaseapp.com',
    storageBucket: 'court-diary-ceadc.firebasestorage.app',
    measurementId: 'G-MDFNP18E7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUiuehVsBFYWvlt0t-WLwshZLiugRRQa0',
    appId: '1:211588944864:android:622a460e11bdfe4b119185',
    messagingSenderId: '211588944864',
    projectId: 'court-diary-ceadc',
    storageBucket: 'court-diary-ceadc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_CLtZYBkDIwdkOCM8wVK8to6UIaUkggU',
    appId: '1:211588944864:ios:d58a7d5de80b2d20119185',
    messagingSenderId: '211588944864',
    projectId: 'court-diary-ceadc',
    storageBucket: 'court-diary-ceadc.firebasestorage.app',
    iosBundleId: 'com.appseba.courtdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_CLtZYBkDIwdkOCM8wVK8to6UIaUkggU',
    appId: '1:211588944864:ios:db2e84a1a5074636119185',
    messagingSenderId: '211588944864',
    projectId: 'court-diary-ceadc',
    storageBucket: 'court-diary-ceadc.firebasestorage.app',
    iosBundleId: 'com.example.courtdiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiVjiYk4P_iupB825akQCiG3M2Wn5RSeU',
    appId: '1:211588944864:web:8fe8f41a3874cf42119185',
    messagingSenderId: '211588944864',
    projectId: 'court-diary-ceadc',
    authDomain: 'court-diary-ceadc.firebaseapp.com',
    storageBucket: 'court-diary-ceadc.firebasestorage.app',
    measurementId: 'G-W0706GYHRY',
  );
}
