// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmLzlb5G87uYGChq2q5JXZdiVYNeerXXg',
    appId: '1:648379937710:web:6f3073b3059a4a13b0ce3f',
    messagingSenderId: '648379937710',
    projectId: 'seba-pos-52e7a',
    authDomain: 'seba-pos-52e7a.firebaseapp.com',
    storageBucket: 'seba-pos-52e7a.firebasestorage.app',
    measurementId: 'G-SY9F594E0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmQIlUqy8g99ZYaY_0gq5Cq8s4Zlw2gs',
    appId: '1:648379937710:android:61400c1cbc12db80b0ce3f',
    messagingSenderId: '648379937710',
    projectId: 'seba-pos-52e7a',
    storageBucket: 'seba-pos-52e7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAredjyS7QD-jQxNbC0mQ41yQOuJ8yQJ3o',
    appId: '1:648379937710:ios:af7f9f74c8f08299b0ce3f',
    messagingSenderId: '648379937710',
    projectId: 'seba-pos-52e7a',
    storageBucket: 'seba-pos-52e7a.firebasestorage.app',
    iosClientId: '648379937710-kn35rjoqcuqjulido8od9l3obmaeufkj.apps.googleusercontent.com',
    iosBundleId: 'com.appseba.sebapos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAredjyS7QD-jQxNbC0mQ41yQOuJ8yQJ3o',
    appId: '1:648379937710:ios:6ff27f66ef382f2fb0ce3f',
    messagingSenderId: '648379937710',
    projectId: 'seba-pos-52e7a',
    storageBucket: 'seba-pos-52e7a.firebasestorage.app',
    iosClientId: '648379937710-dops225ol8eaperno9t8dsjftcicrtq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalaccounts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmLzlb5G87uYGChq2q5JXZdiVYNeerXXg',
    appId: '1:648379937710:web:6aedc35c57e2cfceb0ce3f',
    messagingSenderId: '648379937710',
    projectId: 'seba-pos-52e7a',
    authDomain: 'seba-pos-52e7a.firebaseapp.com',
    storageBucket: 'seba-pos-52e7a.firebasestorage.app',
    measurementId: 'G-L1SPBSEMEW',
  );

}